---
# git clone https://github.com/KennyKristiansen/Ansible.git
# ansible-playbook main.yml -i hosts --tags docker_apps -K
# ansible-playbook main.yml -i hosts -K --connection=local
# the binary | this.file | -i targets | *optional --tags | -K asks for sudo pass
# cd .. && sudo rm -r Ansible && git clone https://github.com/KennyKristiansen/Ansible.git && cd Ansible && ansible-playbook main.yml -i hosts -K --connection=local

- hosts: all
  become: true
  vars:
    PUID: 1050
    PGID: 1050
    TZ: Europe/Copenhagen
    docker-compose-version: "3.8"
  roles:
    - ansible-update
    - initial-setup
    - docker
    - docker-compose

#    - mergerfs
#    - snapraid
