---
version: "2"
services:
  airsonic-advanced:
    image: airsonicadvanced/airsonic-advanced:latest
    container_name: airsonicadvanced
    restart: unless-stopped
    hostname: ${DOCKERHOSTNAME}
    volumes:
      - /mnt/appdata/airsonic:/config
      - /mnt/storage/music/flac:/music/flac
      - /mnt/appdata/airsonic/var/playlists:/var/playlists
      - /mnt/appdata/airsonic/var/podcasts:/var/podcasts
      - /mnt/appdata/airsonic/var/airsonic:/var/airsonic
      - /mnt/appdata/airsonic/var/music:/var/music
      - /mnt/appdata/airsonic/var/transcode:/var/airsonic/transcode
    ports:
      - 4040:4040
    environment:
    env_file: .env
      - CONTEXT_PATH=/music
      - JAVA_OPTS=-Dserver.use-forward-headers=true
