---
version: "2"
services:
  firefly:
    image: fireflyiii/core:latest
    container_name: fireflyiii
    restart: always
    volumes:
      - firefly_iii_upload:/var/www/html/storage/upload
    env_file: ../etc/user.env
    ports:
      - 89:8090
    depends_on:
      - db
  db:
    image: mariadb    
    hostname: fireflyiiidb
    restart: always
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=firefly
      - MYSQL_PASSWORD=secret_firefly_password
      - MYSQL_DATABASE=firefly
    volumes:
      - firefly_iii_db:/var/lib/mysql
volumes:
   firefly_iii_upload:
   firefly_iii_db: