---
version: "2"
services:
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    env_file: .env
    ports:
      - "${PORT:-8191}:8191"
    restart: unless-stopped 
