---
version: '2'
services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    ports:
      - 3000:3000
    volumes:
      - /mnt/appdata/grafana/provisioning:/etc/grafana/provisioning"
      - /mnt/appdata/grafana/data:/var/lib/grafana/ "
    restart:
      always
#    depends_on:
#     - influxdb
