---
version: "2"
services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    network_mode: host

    restart: always
    env_file: ./etc/.env
    ports:
      - 3000:3000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /mnt/appdata/grafana/provisioning:/etc/grafana/provisioning"
      - /mnt/appdata/grafana/data:/var/lib/grafana/ "
    restart:
      always
    depends_on:
     - influxdb
