---
version: {{ docker-compose-version }}
services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    network_mode: host

    restart: always
    environment:
      - PGID= {{ PGID }}
      - PUID= {{ PUID }}
      - TZ= {{ TZ }}
    ports:
      - 3000:3000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /mnt/appdata/grafana/provisioning:/etc/grafana/provisioning"
      - /mnt/appdata/grafana/data:/var/lib/grafana/ "
    restart:
      always
    depends_on:
     - influxdb
