---      
version: \"3.8\"
services:
  homarr:
    container_name: homarr
    image: ghcr.io/ajnart/homarr:latest
    restart: unless-stopped
    volumes:
      - /mnt/appdata/homarr/config:/app/data/configs
      - /mnt/appdata/homarr/icons:/app/public/icons
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - PGID= {{ PGID }}
      - PUID= {{ PUID }}
      - TZ= {{ TZ }}
    ports:
      - '7575:7575'