---
version: "3"

services:
  overseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    env_file: ../etc/user.env
    environment:
      - JELLYFIN_PublishedServerUrl=http://jellyfin:8096
    ports:
      - 5055:5055
    volumes:
      - /mnt/appdata/jellyseerr/config:/app/config
      - /mnt/storage/tv:/data/tvshows
      - /mnt/storage/movies:/data/movies
    restart: unless-stopped     