---
version: "3"

services:
  overseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    env_file: ../etc/user.env
    ports:
      - 5055:5055
    volumes:
      - /mnt/appdata/jellyseerr/config:/app/config
      - /mnt/storage/tv:/data/tvshows
      - /mnt/storage/movies:/data/movies
      - /mnt:/mnt
      - /var/run/docker.sock:/var/run/docker.sock

    restart: unless-stopped     