---
version: '3.8'
services:
  jenkins:
    image: jenkins/jenkins:lts
    env_file: ../etc/user.env
    privileged: true
    user: root
    ports:
     - 9090:8080
     - 50000:50000
    container_name: jenkins
    volumes:
        - /mnt/appdata/jenkins/configuration:/var/jenkins_home
        - /var/run/docker.sock:/var/run/docker.sock