---
### NOTES
### Standard username: changeme@email.com
### Standard password: MyPassword
version: "2"
services:
  mealie:
    container_name: mealie
    image: ghcr.io/mealie-recipes/mealie:nightly
    restart: always
    ports:
      - 9925:9000
    env_file: ../etc/user.env
    deploy:
      resources:
        limits:
          memory: 1000M # 
    environment:
    # Set Backend ENV Variables Here
      - ALLOW_SIGNUP=true
      - MAX_WORKERS=1
      - WEB_CONCURRENCY=1
      - BASE_URL=https://mealie.yourdomain.com
    volumes:
      - /mnt/appdata/mealie/config:/app/data