---
version: "2"
services:
  nzbhydra2:
    image: hotio/nzbhydra2
    container_name: nzbhydra2
    env_file: .env
    volumes:
      - /mnt/appdata/nzbhydra2/config:/config
    ports:
      - 5076:5076
    restart: unless-stopped