---
version: '2'
services:
  nzbhydra2:
    image: hotio/nzbhydra2
    container_name: nzbhydra2
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    volumes:
      - /mnt/appdata/nzbhydra2/config:/config
    ports:
      - 5076:5076
    restart: unless-stopped