---
version: '2'
services:
  ombi:
    image: ghcr.io/linuxserver/ombi
    container_name: ombi
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
      - BASE_URL=/ombi #optional
    volumes:
      - /opt/appdata/ombi/config:/config
    ports:
      - 3579:3579
    restart: unless-stopped