---
version: {{ docker-compose-version }}
services:
  ombi:
    image: lscr.io/linuxserver/ombi:latest
    container_name: ombi
    environment:
      - PGID= {{ PGID }}
      - PUID= {{ PUID }}
      - TZ= {{ TZ }}
      - BASE_URL=/ombi #optional
    volumes:
      - /mnt/appdata/ombi/config:/config
    ports:
      - 3579:3579
    restart: unless-stopped