---
version: "2"
services:
  ombi:
    image: lscr.io/linuxserver/ombi:latest
    container_name: ombi
    env_file: ../etc/user.env
    environment:
      - BASE_URL=/ombi #optional
    volumes:
      - /mnt/appdata/ombi/config:/config
    ports:
      - 3579:3579
    restart: unless-stopped