---
version: "2"
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    #network_mode: host
    env_file: ../etc/user.env
    environment:
      - VERSION=docker
      - PLEX_CLAIM=claim-xzGfr4Dz94mJ8MwyZztE
    volumes:
      - /mnt/appdata/plex:/config
      - /mnt/storage/tv:/tv
      - /mnt/storage/movies:/movies
    ports:
      - 32400:32400
    restart: unless-stopped

  plexpy:
    image: linuxserver/plexpy
    container_name: plexpy
    depends_on:
      - plex
    volumes:
      - /mnt/appdata/plexpy:/config
      - /mnt/appdata/plex/Library/Application\ Support/Plex\ Media\ Server/Logs:/logs:ro
    ports:
      - 27029:8181
    links:
      - plex
    restart: always
    env_file: ../etc/user.env