---
version: "3.8"
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PGID= {{ PGID }}
      - PUID= {{ PUID }}
      - TZ= {{ TZ }}
      - VERSION=docker
      - PLEX_CLAIM=claim-HKZhH9XJ3Bi-hVLA1o59
    volumes:
      - /mnt/appdata/plex:/config
      - /mnt/storage/tv:/tv
      - /mnt/storage/movies:/movies
    restart: unless-stopped

  plexpy:
    image: linuxserver/plexpy
    container_name: plexpy
    depends_on:
      - plex
    volumes:
      - /mnt/appdata/plexpy:/config
      - /mnt/appdata/plex/Library/Application\ Support/Plex\ Media\ Server/Logs:/logs:ro
    ports:
      - 27029:8181
    links:
      - plex
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
