---
version: "2"
services:
  plex-meta-manager:
    image: meisnate12/plex-meta-manager

    stdin_open: true # docker run -i 
    tty: true        # docker run -t

    hostname: ${DOCKERHOSTNAME}
    command: -c /config/config.yml -t 03:00
    environment:
    env_file: .env
    container_name: plex-meta-manager
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/appdata/plex-meta-manager:/config:rw
      - /mnt:/mnt

