---
version: "3.3"
services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PGID= {{ PGID }}
      - PUID= {{ PUID }}
      - TZ= {{ TZ }}
    volumes:
      - /mnt/appdata/prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped
      
