---
version: "2"
services:
  proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: proxy-manager
    restart: unless-stopped
    env_file: ./etc/.env
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - /mnt/appdata/letsencrypt/data:/data
      - /mnt/appdata/letsencrypt:/etc/letsencrypt
