---
version: "3.8"
services:
  proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: proxy-manager
    restart: unless-stopped
    environment:
      - PGID= {{ PGID }}
      - PUID= {{ PUID }}
      - TZ= {{ TZ }}
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - /mnt/appdata/letsencrypt/data:/data
      - /mnt/appdata/letsencrypt:/etc/letsencrypt
