---
version: "2"
services:
  qbittorrent:
    image: ghcr.io/linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
    env_file: .env
      - WEBUI_PORT=8080
    volumes:
      - /mnt/appdata/qbittorrent/config:/config
      - /mnt:/mnt
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 8080:8080
    restart: unless-stopped
