---
version: "2.1"
services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    env_file: ../etc/user.env
    environment:
      - WEBUI_PORT=9999
    volumes:
      - /mnt/appdata/qbittorrent/config:/config
      - /mnt:/downloads
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 8080:9999
    restart: unless-stopped
