---
version: "2"
services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    env_file: ../etc/user.env
    environment:
      - WEBUI_PORT=8080
    volumes:
      - /mnt/appdata/qbittorrent/config:/config
      - /mnt:/mnt
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 8080:8080
    restart: unless-stopped
