---
version: "2.1"
services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    volumes:
      - /mnt/appdata/radarr:/config
      - /mnt:/mnt
    ports:
      - 7878:7878
    env_file: ../etc/user.env
    restart:
      always