---
version: \"3.8\"
services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    volumes:
      - /mnt/appdata/radarr:/config
      - /mnt:/mnt
    ports:
      - 7878:7878
    environment:
      - PGID= {{ PGID }}
      - PUID= {{ PUID }}
      - TZ= {{ TZ }}
    restart:
      always