---
version: "2"
services:
  smokeping:
    image: linuxserver/smokeping
    container_name: smokeping
    volumes:
      - /mnt/appdata/smokeping/config:/config
      - /mnt/appdata/smokeping/data:/data
    ports:
      - 27025:81
    env_file: ../etc/user.env
    restart: always