---
version: \"3.3\"
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    volumes:
      - /mnt/appdata/sonarr:/config
      - /mnt:/mnt
    ports:
      - 8989:8989
    links:
      - nzbget
    restart: always
    environment:
      - PGID= {{ PGID }}
      - PUID= {{ PUID }}
      - TZ= {{ TZ }}
      
  nzbget:
    image: linuxserver/nzbget
    container_name: nzbget
    volumes:
      - /mnt/appdata/nzbget/config:/config
      - /mnt:/mnt
    ports:
      - 27020:6789
    restart: always
    environment:
      - PGID= {{ PGID }}
      - PUID= {{ PUID }}
      - TZ= {{ TZ }}