---
version: "2"
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    volumes:
      - /mnt/appdata/sonarr:/config
      - /mnt:/mnt
    ports:
      - 8989:8989
    restart: always
    env_file: ../etc/user.env