---
version: "2.1"
services:
  heimdall:
    image: ghcr.io/linuxserver/heimdall
    container_name: heimdall
    environment:
    env_file: .env
    volumes:
      - /mnt/appdata/heimdall/config:/config
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped