---
version: '2'
services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    restart: always
    ports:
      - 8086:8086
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /mnt/appdata/influxdb:/var/lib/influxdb
      - /mnt/appdata/influxdb/etc:/etc/influxdb
    restart:
      always
