---
version: "2"
services:
  jackett:
    image: ghcr.io/linuxserver/jackett
    container_name: jackett
    env_file: ./etc/.env
      - AUTO_UPDATE=true #optional
      - RUN_OPTS=<run options here> #optional
    volumes:
      - /mnt/appdata/jackett/config:/config
      - /mnt:/mnt
    ports:
      - 9117:9117
    restart: unless-stopped