---
version: "3.3"
services:
  letsencrypt:
    image: linuxserver/letsencrypt
    container_name: letsencrypt
    ports:
      - 443:443
    volumes:
      - /mnt/appdata/letsencrypt:/config
    restart:
      always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - EMAIL=kennykristiansen@hotmail.com
      - URL=domain.tld
      - SUBDOMAINS=one,sub,domain,comma,separated
      - ONLY_SUBDOMAINS=true
      - DHLEVEL=4096
      - TZ=${TZ}
