---
version: "2"

services:
  overseerr:
    image: sctx/overseerr:latest
    container_name: overseerr
    env_file: ../etc/user.env
    ports:
      - 5055:5055
    volumes:
      - /mnt/appdata/overseerr/config:/app/config
    restart: unless-stopped     