---
- name: ensure os is up to date
  apt:
    update_cache: yes
    upgrade: full
    cache_valid_time: 3600

- name: Install required system packages
  package:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - python3-pip
      - virtualenv
      - python3-setuptools
    state: latest

- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu focal stable
    state: present

- name: Update apt and install docker-ce
  package:
    name:
      - docker-ce
      - docker-compose
    state: latest


- name: Install Docker module for Python
  pip:
    name: docker
    
- name: Install system packages
  package:
    name:
      - curl
      - glances                   # Monitoring tool 
      - git
      - mc                        # Fileviewer
      - wget
      - openssh-server
      - ncdu                      # Overview of disk usage
      - nmap
      - python3
      - sudo
      - tree                      # Replacement of ls command for a tree structured view
      - tmux                      # Run multiple terminal sessions at once
      - net-tools                 # Install useful networking tools
  #    - bash-completion    
  #    - reptyr                   # Take over process from new terminal
  #    - screen                   # Control multiple terminals from one
  #    - smartmontools            # Test hardrives and their SMART statistics
  #    - xfsprogs                 # Utilities for managing the XFS filesystem 
  #    - htop                     # Used to view processes
  #    - iftop                    # Used to view network bandwidth
  #    - iotop                    # Used to view IO bottlenecks
  #    - jq                       # JSON processor for transforming JSON files
  #    - lynx                     # Textbrowser for WWW
    state: latest
  async: 120
  poll: 1  

# - name: Create a ext4 filesystem on /dev/sdb
#  filesystem:
#    fstype: ext4
#    dev: /dev/sdb
    
#- name: Create a ext4 filesystem on /dev/sdc
#  filesystem:
#    fstype: ext4
#   dev: /dev/sdc

- name: create /mnt points
  file:
    dest: "/mnt/{{ item }}"
    state: directory
    owner: dockeruser
    group: dockergroup
    mode: 0777
  with_items: "{{ mntpoints }}"

- name: "Uninstall HTTPD/Apache"
  tags: uninstall_apache
  apt:
    name: httpd
    autoremove: yes
    state: absent
