---
- name: ensure os is up to date
  apt:
    update_cache: yes
    upgrade: full
    cache_valid_time: 3600


- name: Install apt-transport-https
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - lsb-release
      - gnupg
    state: latest
    update_cache: true

- name: Add signing key
  ansible.builtin.apt_key:
    url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
    state: present

- name: Add repository into sources list
  ansible.builtin.apt_repository:
    repo: "deb [arch={{ ansible_architecture }}] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
    state: present
    filename: docker

- name: Install Docker
  ansible.builtin.apt:
    name:
      - docker
      - docker.io
      - docker-compose
      - docker-registry
    state: latest
    update_cache: true

- name: Install system packages
  apt:
    name: [ 'bash-completion',
    'curl',
    'exiftool',
    'fuse',
    'glances',
    'git',
    'htop',
    'iftop',
    'iotop',
    'jq',
    'lynx',
    'mc',
    'wget',
    'xfsprogs',
    'openssh-server',
    'ncdu',
    'nmap',
    'python',
    'reptyr',
    'screen',
    'smartmontools',
    'sudo',
    'tree',
    'tmux']
    state: present
    update_cache: true
    cache_valid_time: 3600

  async: 30
  poll: 1  

# - name: Create a ext4 filesystem on /dev/sdb
#  filesystem:
#    fstype: ext4
#    dev: /dev/sdb
    
#- name: Create a ext4 filesystem on /dev/sdc
#  filesystem:
#    fstype: ext4
#   dev: /dev/sdc

- name: create /mnt points
  file:
    dest: "/mnt/{{ item }}"
    state: directory
    owner: nobody
    group: nogroup
    mode: 0777
  with_items: "{{ mntpoints }}"

#- name: mount sdc
#  mount:
#    path: /mnt/storage
#    src: /dev/sdc
#    fstype: ext4
#    opts: "errors=remount-ro,noatime,user_xattr,acl"
#    # change to 'mounted' to auto mount
#    state: present

#- name: mount mergerfs array
#  mount:
#    name: /mnt/storage
#    src: /mnt/disk*
#    # try to fix issue with nonempty opts
#    opts: direct_io,defaults,allow_other,minfreespace=50G,fsname=mergerfs, nonempty
#    fstype: fuse.mergerfs
#    # change to 'mounted' to auto mount
#    state: present

- name: "1. Uninstall HTTPD/Apache"
  tags: uninstall_apache
  yum:
    name: httpd
    autoremove: yes
    state: absent
