---
- name: ensure os is up to date
  apt:
    update_cache: yes
    upgrade: full
    cache_valid_time: 3600


- name: Install required system packages
  apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - python3-pip
      - virtualenv
      - python3-setuptools
    state: latest
    update_cache: true

- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu focal stable
    state: present

- name: Update apt and install docker-ce
  apt:
    pkg:
      - docker-ce
      - docker-compose
    state: latest
    update_cache: true

- name: Install Docker Module for Python
  pip:
    name: docker
    
- name: Install system packages
  apt:
    name: [ 'bash-completion',
    'curl',
    'exiftool',
    'fuse',
    'glances',
    'git',
    'htop',
    'iftop',
    'iotop',
    'jq',
    'lynx',
    'mc',
    'wget',
    'xfsprogs',
    'openssh-server',
    'ncdu',
    'nmap',
    'python',
    'reptyr',
    'screen',
    'smartmontools',
    'sudo',
    'tree',
    'tmux']
    state: present
    update_cache: true
    cache_valid_time: 3600

  async: 30
  poll: 1  

# - name: Create a ext4 filesystem on /dev/sdb
#  filesystem:
#    fstype: ext4
#    dev: /dev/sdb
    
#- name: Create a ext4 filesystem on /dev/sdc
#  filesystem:
#    fstype: ext4
#   dev: /dev/sdc

- name: create /mnt points
  file:
    dest: "/mnt/{{ item }}"
    state: directory
    owner: nobody
    group: nogroup
    mode: 0777
  with_items: "{{ mntpoints }}"

#- name: mount sdc
#  mount:
#    path: /mnt/storage
#    src: /dev/sdc
#    fstype: ext4
#    opts: "errors=remount-ro,noatime,user_xattr,acl"
#    # change to 'mounted' to auto mount
#    state: present

#- name: mount mergerfs array
#  mount:
#    name: /mnt/storage
#    src: /mnt/disk*
#    # try to fix issue with nonempty opts
#    opts: direct_io,defaults,allow_other,minfreespace=50G,fsname=mergerfs, nonempty
#    fstype: fuse.mergerfs
#    # change to 'mounted' to auto mount
#    state: present

- name: "1. Uninstall HTTPD/Apache"
  tags: uninstall_apache
  yum:
    name: httpd
    autoremove: yes
    state: absent
