---
- name: copy docker-compose.yml into position
  copy:
    src: "opt/{{ item }}.yml"
    dest: "/opt/{{ item }}.yml"
    owner: nobody
    group: nogroup
    mode: 0775
  loop: [ 'plex',
    'heimdall',
    'sonarr',
    'radarr',
    'resilio-sync',
    'airsonicadvanced',
    'influxdb',
    'grafana',
    'plex-meta-manager',
    'bazarr',
    'jackett',
    'portainer',
    'nzbhydra2',
    'flaresolverr',
    'qbittorrent',
    'ombi',
    'mealie',
    'smokeping',
    'watchtower',
    'prowlarr']


#- name: use docker-compose to bring up apps
#  shell: docker-compose -f /opt/docker-compose.yml up -d
