---
#- name: copy docker-compose.yml into position
#  copy:
#    src: "opt/"
#    dest: "/opt/"
#    owner: nobody
#    group: nogroup
#    mode: 0775


- name: Docker-compose up
  docker_compose:
    build: no
    state: present
    project_src: "opt/"
    files: "{{ item }}"
  with_fileglob: 
    - "/opt/*.yml"
  async : 60
  poll: 05


  #- name: Tear down Docker services
#  docker_compose:
#    project_src: "/opt"
#    remove_orphans: yes
#    state: absent

#- name: Docker-compose build
#  docker_compose:
#    pull: yes
#    project_src: "/opt"
#    debug: yes
#  register: actions
#  debug:
#    msg: "{{ actions }}"

#- name: Docker prune
#  docker_prune:
#    containers: yes
#    images: yes
