---
- name: copy docker-compose.yml into position
  copy:
    src: "opt/"
    dest: "/opt/"
    owner: nobody
    group: nogroup
    mode: 0775
  tags: compose

- name: copy docker-compose.yml into position
  copy:
    src: "etc/"
    dest: "/etc/"
    owner: nobody
    group: nogroup
    mode: 0775
  tags: compose

# - name: Stable diffusion webui git clone
#   ansible.builtin.git:
#     repo: "https://github.com/AbdBarho/stable-diffusion-webui-docker.git"
#     clone: true
#     dest: ./etc/
#   tags: compose


# - name: Docker-compose stable diffusion up
#   docker_compose:
#     pull: yes
#     build: yes
#     profiles: download
#     state: present
#     project_src: "/etc/"
#     remove_orphans: false
#   tags: compose


# - name: OpenProject docker-compose up
#   docker_compose:
#     build: no
#     state: present
#     project_src: "./etc/openproject/compose"

- name: Ensure group dockergroup exists
  group:
    name: dockergroup
    state: present
    gid: 1050

- name: Create users
  user:
    name: dockeruser
    state: present
    password: docker
    shell: /bin/bash
    group: dockergroup
    uid: 1050

- name: Get compose files on remote machine
  find:
    paths: "/opt/"
    patterns: "*.yml"
  register: compose_files
  tags: compose

- name: Docker-compose up
  docker_compose:
    pull: yes
    build: yes
    state: present
    project_src: "/opt/"
    files: "{{ item.path | basename }}"
    remove_orphans: false
  loop: "{{ compose_files.files }}"
  loop_control:
    label: "{{ item.path | basename }}"
  tags: compose
  #async : 120
  #poll: 10


# - name: Tear down Docker services
#   docker_compose:
#     project_src: "/opt"
#     remove_orphans: yes
#     state: absent

#- name: Docker-compose build
#  docker_compose:
#    pull: yes
#    project_src: "/opt"
#    debug: yes
#  register: actions
#  debug:
#    msg: "{{ actions }}"

#- name: Docker prune
#  docker_prune:
#    containers: yes
#    images: yes
