---  
  
# UPGRADE AND INSTALL REQUIRED UBUNTU PACKAGES
- name: Update apt cache
  apt: update_cache=yes cache_valid_time=3600

- name: Upgrade all apt packages
  apt: upgrade=dist

- name: Install dependencies
  apt: name={{ item }} state=latest update_cache=yes
  loop: ['apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'gnupg-agent']

# DOCKER INSTALLATION
- name: Add an apt signing key for Docker
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add apt repository for stable version
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
    state: present

- name: Install Docker
  apt: name={{ item }} state=latest update_cache=yes
  loop: ['docker-ce', 'docker-ce-cli', 'containerd.io']

- name: Add user to docker group
  user:
    name: "{{ansible_user}}"
    group: docker

- name: Download docker-compose {{ docker_compose_version }}
  get_url:
    url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
    dest: ~/docker-compose
    mode: "+x"

- name: Check docker-compose exists
  stat: path=~/docker-compose
  register: docker_compose

- name: Move docker-compose to /usr/local/bin/docker-compose
  become: yes
  command: mv ~/docker-compose /usr/local/bin/docker-compose
  when: docker_compose.stat.exists

# REQUIRED PACKAGES FOR USING ANSIBLE DOCKER (for portainer installation below)
- name: Install related Ubuntu packages
  apt: name={{ item }} state=latest update_cache=yes
  loop: ['python3-pip', 'mc']

- name: Install python packages
  pip:
    name: docker-compose

#- name: Tear down Docker services
#  docker_compose:
#    project_src: "/opt"
#    remove_orphans: yes
#    state: absent

#- name: Docker-compose build
#  docker_compose:
#    pull: yes
#    project_src: "/opt"
#    debug: yes
#  register: actions
#  debug:
#    msg: "{{ actions }}"

- name: Docker prune
  docker_prune:
    containers: yes
    images: yes
    dangling: true
    volumes: true

- name: Docker-compose up
  docker_compose:
    build: yes
    state: present
    project_src: "/opt"
    files: "{{ item }}.yml"
  loop: [ 'plex',
  'sonarr',
  'radarr',
  'resilio-sync',
  'letsencrypt',
  'airsonicadvanced',
  'influxdb',
  'grafana',
  'plex-meta-manager',
  'bazarr',
  'jackett',
  'portainer',
  'nzbhydra2',
  'flaresolverr',
  'qbittorrent',
  'ombi',
  'mealie',
  'heimdall',
  'smokeping']

 