---  
  #- name: Tear down Docker services
#  docker_compose:
#    project_src: "/opt"
#    remove_orphans: yes
#    state: absent

#- name: Docker-compose build
#  docker_compose:
#    pull: yes
#    project_src: "/opt"
#    debug: yes
#  register: actions
#  debug:
#    msg: "{{ actions }}"

#- name: Docker prune
#  docker_prune:
#    containers: yes
#    images: yes

- name: configure docker apps (usenet, plex, etc)
  include: docker-apps.yml
  when: docker_apps
  tags: docker_apps


- name: Docker-compose up
  docker_compose:
    build: yes
    state: present
    project_src: "/opt"
    files: "{{ item }}.yml"
  loop: [ 'plex',
  'heimdall',
  'sonarr',
  'radarr',
  'resilio-sync',
  'airsonicadvanced',
  'influxdb',
  'grafana',
  'plex-meta-manager',
  'bazarr',
  'jackett',
  'portainer',
  'nzbhydra2',
  'flaresolverr',
  'qbittorrent',
  'ombi',
  'mealie',
  'smokeping',
  'watchtower',
  'prowlarr']

 