---
#- name: copy docker-compose.yml into position
#  copy:
#    src: "opt/"
#    dest: "/opt/"
#    owner: nobody
#    group: nogroup
#    mode: 0775

# - name: OpenProject git clone
#   ansible.builtin.git:
#     repo: 'https://github.com/opf/openproject-deploy'
#     depth: 1
#     dest: ./etc/openproject

# - name: OpenProject docker-compose up
#   docker_compose:
#     build: no
#     state: present
#     project_src: "./etc/openproject/compose"

- name: Ensure group dockergroup exists
  group:
    name: dockergroup
    state: present
    gid: 1050

- name: Create users
  user:
    name: dockeruser
    state: present
    password: docker
    shell: /bin/bash
    group: dockergroup
    uid: 1050

- name: Docker-compose up
  docker_compose:
    build: yes
    state: present
    project_src: "opt/"
    files: "{{ item }}"
    remove_orphans: false
  with_fileglob: 
    - "opt/*.yml"
  #async : 120
  #poll: 10


# - name: Tear down Docker services
#   docker_compose:
#     project_src: "/opt"
#     remove_orphans: yes
#     state: absent

#- name: Docker-compose build
#  docker_compose:
#    pull: yes
#    project_src: "/opt"
#    debug: yes
#  register: actions
#  debug:
#    msg: "{{ actions }}"

#- name: Docker prune
#  docker_prune:
#    containers: yes
#    images: yes
