---
- name: copy docker-compose.yml into position
  copy:
    src: "opt/{{ item }}.yml"
    dest: "/opt/{{ item }}.yml"
    owner: nobody
    group: nogroup
    mode: 0775
  loop: [ 'plex',
    'heimdall',
    'sonarr',
    'radarr',
    'resilio-sync',
    'airsonicadvanced',
    'influxdb',
    'grafana',
    'plex-meta-manager',
    'bazarr',
    'jackett',
    'portainer',
    'nzbhydra2',
    'flaresolverr',
    'qbittorrent',
    'ombi',
    'mealie',
    'smokeping',
    'watchtower',
    'prowlarr',
    'homarr']


- name: Docker-compose up
  docker_compose:
    build: yes
    state: present
    project_src: "/opt"
    files: "{{ item }}"
  with_fileglob: 
    - "/opt/*.yml"


  #- name: Tear down Docker services
#  docker_compose:
#    project_src: "/opt"
#    remove_orphans: yes
#    state: absent

#- name: Docker-compose build
#  docker_compose:
#    pull: yes
#    project_src: "/opt"
#    debug: yes
#  register: actions
#  debug:
#    msg: "{{ actions }}"

#- name: Docker prune
#  docker_prune:
#    containers: yes
#    images: yes
