---
version: '2'
services:
  bazarr:
    image: ghcr.io/linuxserver/bazarr
    container_name: bazarr
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    volumes:
      - /opt/appdata/bazarr/config:/config
      - /mnt/storage/movies:/movies #optional
      - /mnt/storage/tv:/tv #optional
    ports:
      - 6767:6767
    restart: unless-stopped

