---
version: '2'
services:
  plex:
    image: plexinc/pms-docker
    container_name: plex
    volumes:
      - /opt/appdata/plex:/config
      - /mnt/storage:/data
      - /mnt/storage/transcode:/transcode
    network_mode: host
    restart: always
    environment:
      - PLEX_CLAIM="nope"
      - PUID=${PUID}
      - PGID=${PGID}

  plexpy:
    image: linuxserver/plexpy
    container_name: plexpy
    depends_on:
      - plex
    volumes:
      - /opt/appdata/plexpy:/config
      - /opt/appdata/plex/Library/Application\ Support/Plex\ Media\ Server/Logs:/logs:ro
    ports:
      - 27029:8181
    links:
      - plex
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}

  nzbget:
    image: linuxserver/nzbget
    container_name: nzbget
    volumes:
      - /opt/appdata/nzbget/config:/config
      - /mnt/storage/downloads:/downloads
      - /mnt/storage/downloads/complete:/downloads/complete
    ports:
      - 27020:6789
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}

  sonarr:
    image: ghcr.io/linuxserver/sonarr
    container_name: sonarr
    volumes:
      - /opt/appdata/sonarr:/config
      - /mnt/storage/tv:/tv
      - /mnt/storage/downloads/complete/tv:/downloads
      - /mnt/storage/downloads/complete/tv_import:/tv_import
    ports:
      - 8989:8989
    links:
      - nzbget
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    volumes:
      - /opt/appdata/radarr:/config
      - /mnt/storage/movies:/movies
      - /mnt/storage/downloads/complete/movies:/downloads
    ports:
      - 7878:7878
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    restart:
      always

  geoip-updater:
    image: crazymax/geoip-updater:latest
    container_name: geoip
    volumes:
      - "./data/geoip:/data"
    environment:
      - Europe/London
      - EDITION_IDS=GeoLite2-City,GeoLite2-Country
      - LICENSE_KEY=x1nPZNcjR7eYlYZm
      - DOWNLOAD_PATH=/data
      - SCHEDULE=0 0 * * 0
      - LOG_LEVEL=info
      - LOG_JSON=false
    restart: always

  rtorrent-rutorrent:
    image: crazymax/rtorrent-rutorrent:latest
    container_name: rutorrent

    expose:
      - "6881/udp"
      - "8000"
      - "8080"
      - "9000"
      - "50000"
    ports:
      - target: 6881
        published: 6881
        protocol: udp
      - target: 8080
        published: 8080
        protocol: tcp
      - target: 9000
        published: 9001
        protocol: tcp
      - target: 50000
        published: 50000
        protocol: tcp
    environment:
      - TZ=Europe/Paris
      - PUID=${PUID}
      - PGID=${PGID}
#     - MEMORY_LIMIT=256M
      - UPLOAD_MAX_SIZE=16M
      - OPCACHE_MEM_SIZE=128
      - MAX_FILE_UPLOADS=50
      - REAL_IP_FROM=0.0.0.0/32
      - REAL_IP_HEADER=X-Forwarded-For
      - LOG_IP_VAR=remote_addr

      - XMLRPC_AUTHBASIC_STRING=rTorrent XMLRPC restricted access
      - RUTORRENT_AUTHBASIC_STRING=ruTorrent restricted access
      - WEBDAV_AUTHBASIC_STRING=WebDAV restricted access

      - RT_LOG_LEVEL=info
      - RT_LOG_EXECUTE=false
      - RT_LOG_XMLRPC=false

      - RU_REMOVE_CORE_PLUGINS=erasedata,httprpc
      - RU_HTTP_USER_AGENT=Mozilla/5.0 (Windows NT 6.0; WOW64; rv:12.0) Gecko/20100101 Firefox/12.0
      - RU_HTTP_TIME_OUT=30
      - RU_HTTP_USE_GZIP=true
      - RU_RPC_TIME_OUT=5
      - RU_LOG_RPC_CALLS=false
      - RU_LOG_RPC_FAULTS=true
      - RU_PHP_USE_GZIP=false
      - RU_PHP_GZIP_LEVEL=2
      - RU_SCHEDULE_RAND=10
      - RU_LOG_FILE=/data/rutorrent/rutorrent.log
      - RU_DO_DIAGNOSTIC=true
      - RU_SAVE_UPLOADED_TORRENTS=true
      - RU_OVERWRITE_UPLOADED_TORRENTS=false
      - RU_FORBID_USER_SETTINGS=false
      - RU_LOCALE=UTF8
    volumes:
      - "/opt/appdata/rutorrent/config:/data"
      - "/mnt/storage/downloads:/downloads"
      - "/opt/appdata/rutorrent/passwd:/passwd"
    ulimits:
      nproc: 1024
      nofile:
        soft: 32000
        hard: 40000
    restart: always

#  rtorrent-logs:
#    image: bash
#    command: bash -c 'tail -f /log/*.log'
#    depends_on:
#      - rtorrent-rutorrent
#    volumes:
#      - "./data/rtorrent/log:/log"
#    restart: always

  sync:
    image: linuxserver/resilio-sync
    container_name: sync
    volumes:
      - /opt/appdata/sync:/config
      - /mnt/storage:/sync
    ports:
      - 27028:8888
      - 55555:55555
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    restart: always

  smokeping:
    image: linuxserver/smokeping
    container_name: smokeping
    volumes:
      - /opt/appdata/smokeping/config:/config
      - /opt/appdata/smokeping/data:/data
    ports:
      - 27025:81
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    restart: always

  letsencrypt:
    image: linuxserver/letsencrypt
    container_name: letsencrypt
    ports:
      - 443:443
    volumes:
      - /opt/appdata/letsencrypt:/config
    restart:
      always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - EMAIL=kennykristiansen@hotmail.com
      - URL=domain.tld
      - SUBDOMAINS=one,sub,domain,comma,separated
      - ONLY_SUBDOMAINS=true
      - DHLEVEL=4096
      - TZ=Europe/London

  airsonic-advanced:
    image: airsonicadvanced/airsonic-advanced:latest
    container_name: airsonicadvanced
    restart: unless-stopped
    hostname: ${DOCKERHOSTNAME}
    volumes:
      - /opt/appdata/airsonic:/config
      - /mnt/storage/music/flac:/music/flac
      - /opt/appdata/airsonic/var/playlists:/var/playlists
      - /opt/appdata/airsonic/var/podcasts:/var/podcasts
      - /opt/appdata/airsonic/var/airsonic:/var/airsonic
      - /opt/appdata/airsonic/var/music:/var/music

    environment:
     - PGID=${PGID}
     - PUID=${PUID}
     - TZ=${TZ}
     - CONTEXT_PATH=/music
     - JAVA_OPTS=-Dserver.use-forward-headers=true

  influxdb:
    image: influxdb:latest
    container_name: influxdb
    restart: always
    ports:
      - 8086:8086
    volumes:
      - /opt/appdata/influxdb:/var/lib/influxdb
      - /opt/appdata/influxdb:/var/lib/influxdb2
      - /opt/appdata/influxdb/etc:/etc/influxdb2
    restart:
      always

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    ports:
      - 3002:3000
    volumes:
      - /opt/appdata/grafana:/var/lib/grafana
    restart:
      always

  plex-meta-manager:
    image: meisnate12/plex-meta-manager
    stdin_open: true # docker run -i 
    tty: true        # docker run -t

    hostname: ${DOCKERHOSTNAME}
    command: -c /config/config.yml -t 03:00
    environment:
     - PGID=${PGID}
     - PUID=${PUID}
     - TZ=${TZ}
    container_name: plex-meta-manager
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/appdata/plex-meta-manager:/config:rw
      - /mnt/storage:/storage

  bazarr:
    image: ghcr.io/linuxserver/bazarr
    container_name: bazarr
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=Europe/London
    volumes:
      - /opt/appdata/bazarr/config:/config
      - /mnt/storage/movies:/movies #optional
      - /mnt/storage/tv:/tv #optional
    ports:
      - 6767:6767
    restart: unless-stopped

  jackett:
    image: ghcr.io/linuxserver/jackett
    container_name: jackett
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=Europe/London
      - AUTO_UPDATE=true #optional
      - RUN_OPTS=<run options here> #optional
    volumes:
      - /opt/appdata/jackett/config:/config
      - /mnt/storage/downloads:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped

  portainer:
    container_name: portainer
    image: portainer/portainer-ce
    command: -H unix:///var/run/docker.sock
    restart: always
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/appdata/portainer/data:/data

  nzbhydra2:
    image: ghcr.io/linuxserver/nzbhydra2
    container_name: nzbhydra2
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=Europe/London
    volumes:
      - /opt/appdata/nzbhydra2/config:/config
      - /mnt/storage/downloads:/downloads
    ports:
      - 5076:5076
    restart: unless-stopped

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=Europe/London
    ports:
      - "${PORT:-8191}:8191"
    restart: unless-stopped 