---
version: "2.1"
services:
  heimdall:
    image: ghcr.io/linuxserver/heimdall
    container_name: heimdall
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    volumes:
      - /opt/appdata/heimdall/config:/config
    ports:
      - 81:81
      - 443:443
    restart: unless-stopped