---
version: '2'
services:
  jackett:
    image: ghcr.io/linuxserver/jackett
    container_name: jackett
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
      - AUTO_UPDATE=true #optional
      - RUN_OPTS=<run options here> #optional
    volumes:
      - /opt/appdata/jackett/config:/config
      - /mnt:/mnt
    ports:
      - 9117:9117
    restart: unless-stopped