---
version: '2'
services:
  sonarr:
    image: ghcr.io/linuxserver/sonarr
    container_name: sonarr
    volumes:
      - /opt/appdata/sonarr:/config
      - /mnt:/mnt
    ports:
      - 8989:8989
    links:
      - nzbget
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      