---
version: '2'
services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    ports:
      - 3002:3000
    volumes:
      - /mnt/appdata/grafana:/var/lib/grafana
      - /mnt/appdata/grafana/plugins:/var/lib/grafana/plugins
    user: "1050"
    restart:
      always
