---
version: '2'
services:
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    volumes:
      - /mnt/appdata/radarr:/config
      - /mnt:/mnt
    ports:
      - 7878:7878
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    restart:
      always