---
- name: ensure os is up to date
  apt:
    update_cache: yes
    upgrade: full
    cache_valid_time: 300

- name: Install system packages
  apt: name={{ item }} state=present update_cache=yes
  loop: [ 'bash-completion',
    'curl',
    'exiftool',
    'fuse',
    'glances',
    'git',
    'htop',
    'iftop',
    'iotop',
    'jq',
    'lynx',
    'mc',
    'wget',
    'xfsprogs',
    'openssh-server',
    'ncdu',
    'nmap',
    'python',
    'reptyr',
    'screen',
    'smartmontools',
    'sudo',
    'tree',
    'tmux',
    'containerd.io']

- name: create /mnt points
  file:
    dest: "/mnt/{{ item }}"
    state: directory
    owner: nobody
    group: nogroup
    mode: 0777
  with_items: "{{ mntpoints }}"

- name: mount disks
  mount:
    path: "{{ item.name }}"
    src: "{{ item.src }}"
    fstype: "{{ item.fs }}"
    # change to 'mounted' to auto mount
    state: mounted
  with_items:
     - { name: /mnt/disk1, src: ata-ST12000NE0008-2JL101_ZHZ75XEV-part1, fs: ext4}
#       /dev/disk/by-id/ata-ST12000NE0008-2JL101_ZHZ75XEV
 #   - { name: /mnt/parity1, src: /dev/disk/by-id/ata-WDC_WD60EZRZ-00GZ5B1_WD-WXN1H8449UPL-part1, fs: ext4}
 #   - { name: /mnt/parity2, src: /dev/disk/by-id/ata-WDC_WD80EZZX-11CSGA0_VK0U9B3Y-part1, fs: ext4}
 #   - { name: /mnt/retired.disk2, src: /dev/disk/by-id/ata-Hitachi_HDS5C3030ALA630_MJ1311YNG5SD3A-part1, fs: xfs}
 #   - { name: /mnt/disk3, src: /dev/disk/by-id/ata-WDC_WD30EFRX-68AX9N0_WD-WCC1T0632015-part1, fs: xfs}
 #   - { name: /mnt/disk4, src: /dev/disk/by-id/ata-TOSHIBA_DT01ACA300_X3544DGKS-part1, fs: xfs}
 #   - { name: /mnt/disk5, src: /dev/disk/by-id/ata-WDC_WD30EFRX-68AX9N0_WD-WMC1T0074096-part1, fs: xfs}
     - { name: /mnt/storage, src: /dev/sdc, fs: ext4}

- name: mount mergerfs array
  mount:
    name: /mnt/storage
    src: /mnt/disk*
    opts: direct_io,defaults,allow_other,minfreespace=50G,fsname=mergerfs
    fstype: fuse.mergerfs
    # change to 'mounted' to auto mount
    state: mounted

- name: "1. Uninstall HTTPD/Apache"
  tags: uninstall_apache
  yum:
    name: httpd
    autoremove: yes
    state: absent
